# Generated by Django 5.2.17 on 2026-09-14 11:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='alterado em')),
                ('title', models.CharField(max_length=150, verbose_name='nome')),
                ('slug', models.SlugField(max_length=170, unique=True, verbose_name='identificador')),
                ('summary', models.CharField(max_length=300, verbose_name='descrição')),
                ('objective', models.TextField(verbose_name='objetivo')),
                ('syllabus', models.TextField(verbose_name='conteúdo programático')),
                ('estimated_hours', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='carga horária estimada')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('PUBLISHED', 'Publicada'), ('ARCHIVED', 'Arquivada')], default='DRAFT', max_length=20, verbose_name='situação')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_workshops', to=settings.AUTH_USER_MODEL, verbose_name='criada por')),
            ],
            options={
                'verbose_name': 'oficina',
                'verbose_name_plural': 'oficinas',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='alterado em')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='código')),
                ('title', models.CharField(max_length=150, verbose_name='título')),
                ('location', models.CharField(max_length=255, verbose_name='local')),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='capacidade')),
                ('waitlist_enabled', models.BooleanField(default=True, verbose_name='habilitar lista de espera')),
                ('registration_opens_at', models.DateTimeField(verbose_name='início das inscrições')),
                ('registration_closes_at', models.DateTimeField(verbose_name='fim das inscrições')),
                ('start_date', models.DateField(verbose_name='início das atividades')),
                ('end_date', models.DateField(verbose_name='fim das atividades')),
                ('status', models.CharField(choices=[('PLANNED', 'Planejada'), ('OPEN', 'Inscrições abertas'), ('IN_PROGRESS', 'Em andamento'), ('COMPLETED', 'Concluída'), ('CANCELLED', 'Cancelada')], default='PLANNED', max_length=30, verbose_name='situação')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_class_groups', to=settings.AUTH_USER_MODEL, verbose_name='criada por')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_groups', to='people.institution', verbose_name='instituição parceira')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_groups', to='workshops.workshop', verbose_name='oficina')),
            ],
            options={
                'verbose_name': 'turma',
                'verbose_name_plural': 'turmas',
                'ordering': ['-start_date', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ClassInstructor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='alterado em')),
                ('is_lead', models.BooleanField(default=False, verbose_name='instrutor principal')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='atribuído em')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_links', to='workshops.classgroup', verbose_name='turma')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_links', to='people.instructor', verbose_name='instrutor')),
            ],
            options={
                'verbose_name': 'instrutor da turma',
                'verbose_name_plural': 'instrutores da turma',
                'ordering': ['-is_lead', 'instructor__user__full_name'],
                'constraints': [models.UniqueConstraint(fields=('class_group', 'instructor'), name='workshops_class_instructor_unique'), models.UniqueConstraint(condition=models.Q(('is_lead', True)), fields=('class_group',), name='workshops_class_lead_unique')],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='alterado em')),
                ('title', models.CharField(max_length=150, verbose_name='tema')),
                ('description', models.TextField(blank=True, verbose_name='conteúdo e observações')),
                ('starts_at', models.DateTimeField(verbose_name='início')),
                ('ends_at', models.DateTimeField(verbose_name='fim')),
                ('status', models.CharField(choices=[('PLANNED', 'Planejado'), ('COMPLETED', 'Realizado'), ('CANCELLED', 'Cancelado')], default='PLANNED', max_length=20, verbose_name='situação')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='workshops.classgroup', verbose_name='turma')),
            ],
            options={
                'verbose_name': 'encontro',
                'verbose_name_plural': 'encontros',
                'ordering': ['starts_at'],
                'indexes': [models.Index(fields=['class_group', 'status', 'starts_at'], name='workshops_meeting_schedule_idx')],
                'constraints': [models.UniqueConstraint(fields=('class_group', 'starts_at'), name='workshops_meeting_start_unique'), models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='workshops_meeting_end_after_start')],
            },
        ),
        migrations.AddIndex(
            model_name='workshop',
            index=models.Index(fields=['status'], name='workshops_workshop_status_idx'),
        ),
        migrations.AddIndex(
            model_name='classgroup',
            index=models.Index(fields=['workshop', 'status', 'start_date'], name='workshops_class_search_idx'),
        ),
        migrations.AddConstraint(
            model_name='classgroup',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='workshops_capacity_gt_zero'),
        ),
    ]
