# Generated by Django 5.2.17 on 2026-09-14 11:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('workshops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='alterado em')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('CONFIRMED', 'Confirmada'), ('WAITLISTED', 'Lista de espera'), ('REJECTED', 'Rejeitada'), ('CANCELLED', 'Cancelada'), ('APPROVED', 'Aprovada'), ('NOT_COMPLETED', 'Não concluída')], default='PENDING', max_length=30, verbose_name='situação')),
                ('status_reason', models.TextField(blank=True, verbose_name='motivo da situação')),
                ('waitlisted_at', models.DateTimeField(blank=True, null=True, verbose_name='entrada na lista de espera')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmação')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelamento')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='workshops.classgroup', verbose_name='turma')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='registrada por')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='people.participant', verbose_name='participante')),
            ],
            options={
                'verbose_name': 'inscrição',
                'verbose_name_plural': 'inscrições',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentStatusHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, choices=[('PENDING', 'Pendente'), ('CONFIRMED', 'Confirmada'), ('WAITLISTED', 'Lista de espera'), ('REJECTED', 'Rejeitada'), ('CANCELLED', 'Cancelada'), ('APPROVED', 'Aprovada'), ('NOT_COMPLETED', 'Não concluída')], max_length=30, null=True, verbose_name='situação anterior')),
                ('to_status', models.CharField(choices=[('PENDING', 'Pendente'), ('CONFIRMED', 'Confirmada'), ('WAITLISTED', 'Lista de espera'), ('REJECTED', 'Rejeitada'), ('CANCELLED', 'Cancelada'), ('APPROVED', 'Aprovada'), ('NOT_COMPLETED', 'Não concluída')], max_length=30, verbose_name='nova situação')),
                ('reason', models.TextField(blank=True, verbose_name='motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='alterada em')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='alterada por')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='enrollments.enrollment', verbose_name='inscrição')),
            ],
            options={
                'verbose_name': 'histórico da inscrição',
                'verbose_name_plural': 'históricos das inscrições',
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['class_group', 'status', 'created_at'], name='enrollments_class_status_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['class_group', 'status', 'waitlisted_at'], name='enrollments_waitlist_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('participant', 'class_group'), name='enrollments_participant_class_unique'),
        ),
    ]
