# Generated by Django 5.2.17 on 2026-09-14 11:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollments', '0001_initial'),
        ('workshops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='alterado em')),
                ('status', models.CharField(choices=[('PRESENT', 'Presente'), ('ABSENT', 'Ausente'), ('JUSTIFIED', 'Falta justificada')], max_length=20, verbose_name='situação')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='justificativa ou observação')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='enrollments.enrollment', verbose_name='inscrição')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='workshops.meeting', verbose_name='encontro')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_attendances', to=settings.AUTH_USER_MODEL, verbose_name='registrada por')),
            ],
            options={
                'verbose_name': 'frequência',
                'verbose_name_plural': 'frequências',
                'ordering': ['meeting__starts_at', 'enrollment__participant__full_name'],
                'indexes': [models.Index(fields=['enrollment', 'status'], name='learning_att_enrollment_idx'), models.Index(fields=['meeting', 'status'], name='learning_att_meeting_idx')],
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'meeting'), name='learning_attendance_enrollment_meeting_unique')],
            },
        ),
    ]
