# Generated by Django 5.2.17 on 2026-09-14

import apps.learning.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0001_initial"),
        ("learning", "0002_studentproject_evaluation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="alterado em"),
                ),
                (
                    "verification_code",
                    models.CharField(
                        default=apps.learning.models.generate_certificate_code,
                        editable=False,
                        max_length=40,
                        unique=True,
                        verbose_name="código de identificação",
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="emitido em",
                    ),
                ),
                (
                    "workload_hours",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="carga horária",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="revogado em",
                    ),
                ),
                (
                    "revocation_reason",
                    models.TextField(blank=True, verbose_name="motivo da revogação"),
                ),
                (
                    "enrollment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certificate",
                        to="enrollments.enrollment",
                        verbose_name="inscrição",
                    ),
                ),
            ],
            options={
                "verbose_name": "certificado",
                "verbose_name_plural": "certificados",
                "ordering": ["-issued_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                is_active=True,
                                revoked_at__isnull=True,
                                revocation_reason="",
                            )
                            | (
                                models.Q(is_active=False, revoked_at__isnull=False)
                                & ~models.Q(revocation_reason="")
                            )
                        ),
                        name="learning_certificate_revocation_state",
                    )
                ],
            },
        ),
    ]
