# Generated by Django 5.2.17 on 2026-09-11 14:40

import apps.people.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='alterado em')),
                ('full_name', models.CharField(max_length=150, verbose_name='nome completo')),
                ('phone', models.CharField(max_length=11, validators=[apps.people.validators.validate_phone], verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'responsável',
                'verbose_name_plural': 'responsáveis',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='alterado em')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('document', models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[apps.people.validators.validate_cnpj], verbose_name='CNPJ')),
                ('contact_name', models.CharField(blank=True, max_length=150, verbose_name='pessoa de contato')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail de contato')),
                ('contact_phone', models.CharField(blank=True, max_length=11, validators=[apps.people.validators.validate_phone], verbose_name='telefone de contato')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='endereço')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
            ],
            options={
                'verbose_name': 'instituição parceira',
                'verbose_name_plural': 'instituições parceiras',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='alterado em')),
                ('biography', models.TextField(blank=True, verbose_name='biografia')),
                ('specialties', models.CharField(blank=True, max_length=255, verbose_name='especialidades')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='instructor_profile', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'instrutor',
                'verbose_name_plural': 'instrutores',
                'ordering': ['user__full_name'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='alterado em')),
                ('full_name', models.CharField(max_length=150, verbose_name='nome completo')),
                ('birth_date', models.DateField(verbose_name='data de nascimento')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[apps.people.validators.validate_cpf], verbose_name='CPF')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail de contato')),
                ('phone', models.CharField(blank=True, max_length=11, validators=[apps.people.validators.validate_phone], verbose_name='telefone')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('privacy_consent_at', models.DateTimeField(blank=True, null=True, verbose_name='consentimento de privacidade em')),
                ('image_authorization', models.BooleanField(default=False, verbose_name='autorização de imagem')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participant_profile', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'participante',
                'verbose_name_plural': 'participantes',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantGuardian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='alterado em')),
                ('relationship', models.CharField(choices=[('MOTHER', 'Mãe'), ('FATHER', 'Pai'), ('LEGAL_GUARDIAN', 'Tutor legal'), ('OTHER', 'Outro')], max_length=30, verbose_name='vínculo')),
                ('is_primary', models.BooleanField(default=False, verbose_name='responsável principal')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participant_links', to='people.guardian', verbose_name='responsável')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_links', to='people.participant', verbose_name='participante')),
            ],
            options={
                'verbose_name': 'vínculo com responsável',
                'verbose_name_plural': 'vínculos com responsáveis',
                'ordering': ['-is_primary', 'guardian__full_name'],
                'constraints': [models.UniqueConstraint(fields=('participant', 'guardian'), name='people_participant_guardian_unique'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('participant',), name='people_participant_primary_guardian_unique')],
            },
        ),
    ]
